version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/models:/app/models

  # test:
  #   build: ./api
  #   depends_on:
  #     - api
  #   command: pytest
  #   volumes:
  #     - ./api:/app


  streamlit:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - api