version: "3.8"
services:
  fastapi:
    build: ./api
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - prometheus
      
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/dashboards      
    networks:
      - my_network
    depends_on:
      - prometheus
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - my_network


  streamlit:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - my_network

networks:
  my_network: